{{- if and .Values.autoscaler.enabled .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "coredns.fullname" . }}-autoscaler
  namespace: {{ .Release.Namespace }}
  labels: {{- include "coredns.labels.autoscaler" . | nindent 4 }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.customAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.autoscaler.image.pullSecrets }}
imagePullSecrets:
{{- range . }}
  - name: {{ . }}
{{- end }}
{{- end }}
{{- end }}
