{{- if and .Values.deployment.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "coredns.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "coredns.labels" . | nindent 4 }}
  {{- with merge .Values.serviceAccount.annotations .Values.customAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.image.pullSecrets }}
imagePullSecrets:
{{- range . }}
  - name: {{ . }}
{{- end }}
{{- end }}
{{- end }}
