apiVersion: v2
name: mailpit
description: An email and SMTP testing tool with API for developers
icon: https://raw.githubusercontent.com/axllent/mailpit/develop/server/ui/mailpit.svg
type: application
version: 0.28.0
appVersion: 1.27.1
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 2.x.x
sources:
  - https://github.com/jouve/charts
  - https://github.com/axllent/mailpit
maintainers:
  - name: jouve
    url: https://github.com/jouve
annotations:
  artifacthub.io/license: GPL-3.0-or-later
